default: &default
  adapter: postgresql
  encoding: unicode
  host: database
  port: 5432
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: rails_dev

test:
  <<: *default
  database: rails_test
