base: &base
  encoding: unicode
  pool: 5
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *base

test:
  <<: *base

production:
  primary:
    <<: *base
  cache:
    <<: *base
  queue:
    <<: *base
  cable:
    <<: *base
